[theme]

# Primary accent for interactive elements
primaryColor = '#AD6134'

# Background color for the main content area
backgroundColor = '#141A1f'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#263038'

# Color used for almost all text
textColor = '#FFFFFF'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"
